language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.6
          env: PYVERSION="3"

        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"

install:
    - pip install --upgrade pip setuptools wheel
    - pip install coveralls codecov pyflakes
    - pip install -r requirements.txt
    - pip install git+https://github.com/dvolgyes/TMO4CT

script:
  - make test

after_success:
  - coveralls
  - codecov
